# Generated by Django 3.1.4 on 2020-12-29 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encounter',
            old_name='ID',
            new_name='fightID',
        ),
        migrations.RenameField(
            model_name='fight',
            old_name='b1122',
            new_name='Aegis',
        ),
        migrations.RenameField(
            model_name='fight',
            old_name='b1187',
            new_name='Aegis2',
        ),
        migrations.RenameField(
            model_name='fight',
            old_name='b17674',
            new_name='Alacrity',
        ),
        migrations.RenameField(
            model_name='fight',
            old_name='b17675',
            new_name='Fury',
        ),
        migrations.RenameField(
            model_name='fight',
            old_name='b26980',
            new_name='Might',
        ),
        migrations.RenameField(
            model_name='fight',
            old_name='b30328',
            new_name='Protection',
        ),
        migrations.RenameField(
            model_name='fight',
            old_name='b717',
            new_name='Quickness',
        ),
        migrations.RenameField(
            model_name='fight',
            old_name='b718',
            new_name='Regeneration',
        ),
        migrations.RenameField(
            model_name='fight',
            old_name='b719',
            new_name='Regeneration2',
        ),
        migrations.RenameField(
            model_name='fight',
            old_name='b725',
            new_name='Resistance',
        ),
        migrations.RenameField(
            model_name='fight',
            old_name='b726',
            new_name='Retaliation',
        ),
        migrations.RenameField(
            model_name='fight',
            old_name='b740',
            new_name='Stability',
        ),
        migrations.RenameField(
            model_name='fight',
            old_name='b743',
            new_name='Swiftness',
        ),
        migrations.RenameField(
            model_name='fight',
            old_name='b873',
            new_name='Vigor',
        ),
    ]
