# Generated by Django 3.1.4 on 2020-12-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0002_auto_20201229_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='fightID',
            field=models.IntegerField(),
        ),
    ]
