# Generated by Django 3.1.5 on 2021-03-06 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('icon', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tryID', models.CharField(max_length=40)),
                ('gw2Build', models.IntegerField()),
                ('permaLink', models.URLField()),
                ('cm', models.BooleanField(default=False)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainDB.boss')),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('account', models.CharField(max_length=30)),
                ('archetype', models.CharField(max_length=7)),
                ('DPS', models.IntegerField()),
                ('fury', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('might', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('quickness', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('alacrity', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainDB.fight')),
            ],
        ),
    ]
