# Generated by Django 3.1.4 on 2021-01-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('fightID', models.IntegerField()),
                ('gw2Build', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tryID', models.IntegerField()),
                ('account', models.CharField(max_length=30)),
                ('DPS', models.IntegerField()),
                ('archetype', models.CharField(max_length=7)),
                ('Protection', models.DecimalField(decimal_places=3, max_digits=6)),
                ('Regeneration', models.DecimalField(decimal_places=3, max_digits=6)),
                ('Swiftness', models.DecimalField(decimal_places=3, max_digits=6)),
                ('Fury', models.DecimalField(decimal_places=3, max_digits=6)),
                ('Vigor', models.DecimalField(decimal_places=3, max_digits=6)),
                ('Might', models.DecimalField(decimal_places=3, max_digits=6)),
                ('Aegis', models.DecimalField(decimal_places=3, max_digits=6)),
                ('Retaliation', models.DecimalField(decimal_places=3, max_digits=6)),
                ('Stability', models.DecimalField(decimal_places=3, max_digits=6)),
                ('Quickness', models.DecimalField(decimal_places=3, max_digits=6)),
                ('RG2', models.DecimalField(decimal_places=3, max_digits=6)),
                ('AG2', models.DecimalField(decimal_places=3, max_digits=6)),
                ('Resistance', models.DecimalField(decimal_places=3, max_digits=6)),
                ('Alacrity', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
    ]
