# Generated by Django 3.1.5 on 2021-03-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('tryID', models.CharField(max_length=40)),
                ('account', models.CharField(max_length=30)),
                ('DPS', models.IntegerField()),
                ('archetype', models.CharField(max_length=7)),
                ('gw2Build', models.IntegerField()),
                ('fury', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('might', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('quickness', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('alacrity', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
            ],
        ),
    ]
