# Generated by Django 3.1.4 on 2021-01-01 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encounter',
            old_name='fightID',
            new_name='tryID',
        ),
    ]
